### ISSUE TITLE
'Continue reading' button breaks the markdown formatting

### ISSUE THREAD

**Issue by DaveShuckerow** [AuburnACM/auacm#108]
It looks to me like the truncation needs to support finishing all the open markdown elements; both by adding trailing \* for italics and bold formatting and by not counting non-rendered metadata like links towards the length limit.  Example:

![image](https://cloud.githubusercontent.com/assets/14947366/24129794/24811142-0da2-11e7-9203-9392e9ab39a1.png)

**Comment by Mac-Genius** [comment]
This happens because the markdown is trimmed before it is converted to HTML. I'm currently working on a solution that uses a dfs to trim the markdown after it is converted to HTML.

**Comment by Mac-Genius** [comment]
Fixed by #109
