### ISSUE TITLE
Forgot password

### ISSUE THREAD

**Issue by kirandasika0** [AuburnACM/auacm#123]
Figured I'll just put it here so that the devs can see it. I've been trying to log in, but I think I forgot my password. Is there a way I can get my password back?

**Comment by Mac-Genius** [comment]
Hi @kirandasika98, I can reset your password, but we cannot get your password back. Are you on our slack? I can ping you what I reset it to.

EDIT: Also ping me your username.

**Comment by kirandasika0** [comment]
username: saikiran

No I don't think I'm on your slack.

**Comment by Mac-Genius** [comment]
You can join our slack at https://auburnacm.slack.com. This is an excellent place to stay up to date with the latest ACM news and ask future questions! I will reset your password within the next few hours. I'll give you an update when you can login again!

**Comment by Mac-Genius** [comment]
Your password has been reset and your temporary one has been sent in Slack. Make sure to change it when you login!
