### ISSUE TITLE
Socket should be Python 3 compatible

### ISSUE THREAD

**Issue by WilliamHester** [AuburnACM/auacm#20]
Right now, the library used for Python web sockets is only for Python 2.7. This is the only thing holding us back from being completely Python 3.

**Comment by BrandonLMorris** [comment]
On this issue, Flask-SocketIO has a new version (1.x) that is Python 3.3+ compatible. All that needs to be done is switching over to the new version (it also drops some of the gevent dependencies). [Here's](https://flask-socketio.readthedocs.org/en/latest/) a link to the docs for more info
