### ISSUE TITLE
Investigate alternative database

### ISSUE THREAD

**Issue by WilliamHester** [AuburnACM/auacm#26]
Should look into other kinds of databases that can be used, why they might be better, and what would be needed to migrate to them.

**Comment by BrandonLMorris** [comment]
MongoDB is really cool, but [awful if you're data is at all relational](http://www.sarahmei.com/blog/2013/11/11/why-you-should-never-use-mongodb/) so that's a no-go. MySQL seems to me to be dying to PostgreSQL, but not enough that we should switch. I'm going to go ahead and close this.
