### ISSUE TITLE
Judge/Submission page should show recent submissions

### ISSUE THREAD

**Issue by WilliamHester** [AuburnACM/auacm#29]
Right now the judge/submission page only shows submissions if they are submitted since visiting the page. It would be nice if it showed the 10 most recent submissions of that user, regardless of when they were (similar to Kattis).

**Comment by BrandonLMorris** [comment]
In addition, the submissions should be listed chronologically with the most recent at the top.

**Comment by BrandonLMorris** [comment]
Fixed with #79
