### ISSUE TITLE
Angular 2

### ISSUE THREAD

**Issue by BrandonLMorris** [AuburnACM/auacm#95]
Angular 2 is in beta if not already released. I haven't looked into it, but I'm pretty sure it's a big leap. If we want the site to remain relevant for more than a couple of years, we should seriously consider adopting Angular 2.

**Comment by Mac-Genius** [comment]
Angular 2 has been added to Master. Is this ready to be closed?

**Comment by BrandonLMorris** [comment]
Yes, I'll let you do the honors
